##############################################################
#                      MODIFY THIS FILE                      #
##############################################################
# Modify the 'Resources' section below to create a new AWS   #
# CodePipeline. It should pull the code from GitHub. Then    #
# execute the buildspec.yml file in AWS CodeBuild. And then  #
# finally deploy the imagedefinitions.json file (that comes  #
# out of CodeBuild) to ECS.                                  #
#                                                            #
# Once completed, create a new Stack in CloudFormation AWS   #
# Web Console, with the name 'EUF-Dec2024-USERNAME-Pipeline' #
# and upload this template to that.                          #
##############################################################

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      # Populate CodePipeline properties below this.
      # Here is a link to the documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html

      # YOUR CHANGES HERE

      Tags: # DO NOT MODIFY TAGS
        - Key: Owner
          Value: armand.maree@epiuse.com
        - Key: FIN
          Value: armand.maree@epiuse.com
        - Key: project
          Value: EUF-Dec2024
  CodeBuildProject:
    # To finalize this connection once upload to CloudFormation follow these steps below. This is only needed once:
    # 1) Go to: https://us-east-2.console.aws.amazon.com/codesuite/settings/connections
    # 2) Click on the connection with your username
    # 3) Click on "Update pending connection"
    # 4) IMPORTANT: Make sure to leave the field 'App installation' blank!
    # 5) Click on "Install a new app"
    # 6) On the GitHub screen make sure you select your own GitHub user, not an organization (if there are any).
    # 7) Once you are redirected back to AWS, click "Configure".
    Type: AWS::CodeBuild::Project
    Properties:
      onnectionName: EUF-Dec2024-USERNAME # IMPORTANT: Change this to your username
      ProviderType: GitHub
      Tags: # DO NOT MODIFY TAGS
        - Key: Owner
          Value: armand.maree@epiuse.com
        - Key: FIN
          Value: armand.maree@epiuse.com
        - Key: project
          Value: EUF-Dec2024
